# Generated by Django 2.1 on 2018-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('note2', models.CharField(blank=True, max_length=300, verbose_name='备注2')),
            ],
            options={
                'verbose_name': '投诉',
                'verbose_name_plural': '投诉的数据',
            },
        ),
    ]
